---
namespace: Compile
expectation: Fail
outputs:
  - "Error [ETYC0372017]: The type `Foo` is not found in the current scope.\n    --> compiler-test:4:22\n     |\n   4 | function main(a: u8, foo: Foo) -> u8 {\n     |                      ^^^\nError [ETYC0372017]: The type `Foo` is not found in the current scope.\n    --> compiler-test:9:32\n     |\n   9 | function returns_foo(a: u8) -> Foo {\n     |                                ^^^\nError [ETYC0372003]: Expected type `Foo` but type `u8` was found\n    --> compiler-test:9:22\n     |\n   9 | function returns_foo(a: u8) -> Foo {\n     |                      ^\nError [ETYC0372017]: The type `Foo` is not found in the current scope.\n    --> compiler-test:9:1\n     |\n   9 | function returns_foo(a: u8) -> Foo {\n  10 |     return a;\n  11 | }\n     | ^\n"
